version: '2'

services:

    webapi:
        image: chktr
        environment:
            - ASPNETCORE_ENVIRONMENT=Production

    redis:  
        image: redis
        ports:
            - "6379:6379"

    load_balancer:
        image: haproxy:1.7.1
        volumes:
            - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
        ports:
            - "8181:8080"